### ISSUE TITLE
setup failure

### ISSUE THREAD

**Issue by mkliu** [acburdine/ghost-faker#1]
it always says setup failure, and i checked their API doc
http://api.ghost.org/docs/

looks like there's no API for the setup you are calling?

**Comment by acburdine** [comment]
The api is there, it's just not public and is therefore not listed. 😀

Currently, this is broken because of changes to Ghost that restrict access to _only_ the url from which ghost is intended to be accessed from (e.g. the browser). I haven't had time to work on this recently, but am working on a solution around it.

**Comment by acburdine** [comment]
@mkliu This should be fixed now. I'll be pushing a new release later today.
